name: Go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o app_new main.go

      # Copying files and artifacts via SSH
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          key: ${{ secrets.HOSTLAND_KEY }}
          port: ${{ secrets.HOSTLAND_PORT }}
          source: "app_new"
          target: "${{ secrets.HOSTLAND_TEST_DIR }}"

      # Rerun app on server
      - name: Rerun on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          key: ${{ secrets.HOSTLAND_KEY }}
          port: ${{ secrets.HOSTLAND_PORT }}
          script:
            kill -9 $(pgrep app | awk '{print $1}') &&
            cd ~/trad3r.ru/htdocs/github_actions_test &&
            mv -f app_new app &&
            ./app
